version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: safety_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: safety
      DB_USER: safety_user
      DB_PASSWORD: safety_password
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: safety_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: safety_db
    restart: always
    environment:
      POSTGRES_USER: safety_user
      POSTGRES_PASSWORD: safety_password
      POSTGRES_DB: safety
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

